        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 29 10:47:50 2012
        MODULE DPMEPS__genmod
          INTERFACE 
            FUNCTION DPMEPS
              REAL(KIND=8) :: DPMEPS
            END FUNCTION DPMEPS
          END INTERFACE 
        END MODULE DPMEPS__genmod
